TreeStructureManagement/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeStructureManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Pid { get; set; }
        public string Description { get; set; }
    }
}

TreeStructureManagement/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using TreeStructureManagement.Models;

namespace TreeStructureManagement.ViewModels
{
    public class CategoryViewModel
    {
        [Display(Name = "Category Id")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter Name.")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Parent Id")]
        public int Pid { get; set; }

        [Required(ErrorMessage = "Please enter a description.")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [ForeignKey("Pid")]
        public virtual Category Parent { get; set; }
        public virtual ICollection<Category> Childs { get; set; }
    }
}

TreeStructureManagement/Controllers/CategoriesController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TreeStructureManagement.Models;
using TreeStructureManagement.Repositories;
using TreeStructureManagement.ViewModels;

namespace TreeStructureManagement.Controllers
{
    public class CategoriesController : Controller
    { 
        private IBaseRepository<Category> _repository = null;

        public CategoriesController()
        {
            this._repository = new BaseRepository<Category>();
        }
      
        public async Task<ActionResult> Index(string searchString)
        {
            var categories = _repository.SelectAll().ToList();
            var categoryViewModel = Mapper.Map<IEnumerable<CategoryViewModel>>(categories);

            if (!String.IsNullOrEmpty(searchString))
            {
                categoryViewModel = categoryViewModel.Where(s => s.Name.Contains(searchString));
            }
            await Task.Yield();
            return View(categoryViewModel);
        }

        public async Task<ActionResult> Details(int? id)
        {
            var category = _repository.SelectByID(id.Value);
            var categoryViewModel = Mapper.Map<CategoryViewModel>(category);

            await Task.Yield();
            return View(categoryViewModel);
        }

        public async Task<ActionResult> Create()
        {
            var newCategory = new CategoryViewModel();

            await Task.Yield();
            return View(newCategory);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CategoryViewModel categoryViewModel)
        {
            var category = new Category();
           
            var newCategory = Mapper.Map(categoryViewModel, category);
            _repository.Insert(newCategory);
            _repository.Save();

            await Task.Yield();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int? id)
        {
            var category = _repository.SelectByID(id.Value);
            var viewModel =  new CategoryViewModel();
            var newCategory = Mapper.Map(category, viewModel);

            await Task.Yield();
            return View(newCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, CategoryViewModel categoryViewModel)
        {          
            var category = _repository.SelectByID(id.Value);
            var newCategory = Mapper.Map(categoryViewModel, category);
            _repository.Update(category);
            _repository.Save();

            await Task.Yield();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete()
        { 
            var deletedCategory = new CategoryViewModel();

            await Task.Yield();
            return View(deletedCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CategoryViewModel categoryViewModel, int? id)
        {      
            var category = _repository.SelectByID(id.Value);
            var deletedCategory = Mapper.Map(categoryViewModel, category);
            _repository.Delete(deletedCategory);
            _repository.Save();


            return RedirectToAction("Index");
        }
    }
}

TreeStructureManagement/Views/Categories/Create.cshtml
@model TreeStructureManagement.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create Category</h2>

<div>
    @Html.AntiForgeryToken()

    @using (Html.BeginForm("Create", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <p>@Html.HiddenFor(x => Model.Id)</p>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Pid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div>
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    }
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

TreeStructureManagement/Views/Categories/Delete.cshtml
@model TreeStructureManagement.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete Category</h2>
<h3 style="color:brown">Are you sure you want to delete this?</h3>
<div>
    @using (Html.BeginForm("Delete", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <p style="color:white">@Html.LabelFor(x => Model.Id)</p>

        <div class="form-group">
            <div>
                <a href="../Index" class="btn btn-info">&#9668; Back to List</a>
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    }
</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

TreeStructureManagement/Views/Categories/Details.cshtml
@model TreeStructureManagement.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Category Details</h2>

<div>
    <table class="table table-hover">
        <thead>
            <tr class="info">
                <td>
                    @Html.LabelFor(x => Model.Id)
                </td>
                <td>
                    @Html.LabelFor(x => Model.Name)
                </td>
                <td>
                    @Html.LabelFor(x => Model.Pid)
                </td>
                <td>
                    @Html.LabelFor(x => Model.Description)
                </td>
            </tr>
        </thead>
        <tr>
            <td>
                @Html.DisplayFor(x => Model.Id)
            </td>
            <td>
                @Html.DisplayFor(x => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(x => Model.Pid)
            </td>
            <td>
                @Html.DisplayFor(x => Model.Description)
            </td>
        </tr>
    </table>
</div>
<div class="form-group">
    <div>
        <a href="../Index" class="btn btn-info">&#9668; Back to List</a>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

TreeStructureManagement/Views/Categories/Edit.cshtml
@model TreeStructureManagement.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Category</h2>

<div>
    @Html.AntiForgeryToken()

    @using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Pid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div>
                <a href="../Index" class="btn btn-info">&#9668; Back to List</a>
                <input type="submit" value="Edit" class="btn btn-warning" />
            </div>
        </div>
    }
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

TreeStructureManagement/Views/Categories/Index.cshtml
@model IEnumerable<TreeStructureManagement.ViewModels.CategoryViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-6">
        <h2>Categories</h2>
    </div>
    <div class="col-sm-6" style="margin: 25px 0px 25px 0px;">
        <form asp-controller="Categories" asp-action="Index" class="form-inline">
            <div class="form-group">
                <input type="text" name="SearchString" class="form-control form-rounded" placeholder="Name">
                <input type="submit" value="Search" class="btn btn-group" />
            </div>
        </form>
    </div>
</div>

    <table class="table table-hover">
        @foreach (var item in Model)
        {
            <thead>
                <tr class="success">
                    <td>
                        @Html.LabelFor(x => item.Name)
                    </td>
                    <td>
                        @Html.LabelFor(x => item.Pid)
                    </td>
                    <td>
                        @Html.LabelFor(x => item.Description)
                    </td>
                    <td>
                        <div>
                            <div>
                                <a href="../Categories/Create" class="btn btn-success">Create New</a>
                            </div>
                        </div>
                    </td>
                </tr>
            </thead>

            break;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Pid)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>